# media — FriendlyElec NanoPi R6S (arm64, 64 GB eMMC).
[media_hosts]
media ansible_host=media.home.arpa ansible_user=root

[media_hosts:vars]
base_hostname=media
ansible_python_interpreter=/usr/bin/python3
